In [2]:

import pandas as pd
from sklearn.preprocessing import LabelEncoder,MinMaxScaler,StandardScaler
import seaborn as sns
import numpy as np

In [3]:
df=pd.read_excel(r"C:\Users\ELCOT\Desktop\Sowmiga\Python Workspace\ML\Practice_data.xlsx")

In [4]:
df.sample(5)

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score
26,1012,IT,Male,87.0,7.8,76.0,9.0,83
16,1017,ECE,Female,NaN,6.2,67.0,8.0,75
0,1001,CSE,Male,82.0,7.5,68.0,9.0,78
25,1006,CSE,Male,95.0,9.0,88.0,10.0,94
10,1011,BBA,Male,69.0,4.5,55.0,6.0,62

In [5]:
x=df.drop(["Final_Score"],axis=1)
y=df["Final_Score"]

In [6]:
X = df[
    ["Attendance_Pct",
     "Study_Hours_Per_Day","Internal_Marks","Assignments_Completed"
    ]
]

y = df["Final_Score"]

In [7]:
from sklearn.model_selection import train_test_split

# Optional but recommended: fill missing values before modeling
X = X.fillna(X.mean(numeric_only=True))

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
models={ "logistic regression": LogisticRegression(max_iter=1000),
        "decision tree": DecisionTreeClassifier( max_depth=5,random_state=42),
        "random forest": RandomForestClassifier(n_estimators=100, random_state=42),}
for name,model in models.items():
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    print(f"\n{name}")
    print(classification_report(y_test,y_pred,zero_division=0))

C:\Users\ELCOT\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

logistic regression
              precision    recall  f1-score   support

          66       0.00      0.00      0.00         1
          69       0.00      0.00      0.00         1
          71       0.00      0.00      0.00         0
          72       0.00      0.00      0.00         0
          73       0.00      0.00      0.00         1
          75       0.00      0.00      0.00         0
          77       0.00      0.00      0.00         0
          78       0.00      0.00      0.00         1
          82       0.00      0.00      0.00         1
          83       1.00      1.00      1.00         1
          86       0.00      0.00      0.00         0
          90       0.00      0.00      0.00         1
          94       0.00      0.00      0.00         1
          96       0.00      0.00      0.00         1

    accuracy                           0.11         9
   macro avg       0.07      0.07      0.07         9
weighted avg       0.11      0.11      0.11         9


decision tree
              precision    recall  f1-score   support

          63       0.00      0.00      0.00         0
          66       0.00      0.00      0.00         1
          69       0.00      0.00      0.00         1
          73       0.00      0.00      0.00         1
          78       0.00      0.00      0.00         1
          82       0.00      0.00      0.00         1
          83       0.00      0.00      0.00         1
          86       0.00      0.00      0.00         0
          90       0.00      0.00      0.00         1
          94       0.50      1.00      0.67         1
          96       0.00      0.00      0.00         1

    accuracy                           0.11         9
   macro avg       0.05      0.09      0.06         9
weighted avg       0.06      0.11      0.07         9


random forest
              precision    recall  f1-score   support

          64       0.00      0.00      0.00         0
          66       0.00      0.00      0.00         1
          69       0.00      0.00      0.00         1
          71       0.00      0.00      0.00         0
          73       0.00      0.00      0.00         1
          75       0.00      0.00      0.00         0
          77       0.00      0.00      0.00         0
          78       0.00      0.00      0.00         1
          82       0.00      0.00      0.00         1
          83       0.50      1.00      0.67         1
          86       0.00      0.00      0.00         0
          90       0.00      0.00      0.00         1
          94       0.50      1.00      0.67         1
          96       0.00      0.00      0.00         1

    accuracy                           0.22         9
   macro avg       0.07      0.14      0.10         9
weighted avg       0.11      0.22      0.15         9

New data set

In [20]:
df=pd.read_excel(r"C:\Users\ELCOT\Desktop\Sowmiga\Python Workspace\ML\Practice_data_with_pass_fail.xlsx")

In [10]:
display(df)

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score,pass_fail
0,1001,CSE,Male,82.0,7.5,68.0,9.0,78,Pass
1,1002,IT,Female,91.0,8.2,74.0,10.0,86,Pass
2,1003,ECE,Male,76.0,5.5,61.0,7.0,70,Pass
3,1004,AI&DS,Female,88.0,7.0,79.0,9.0,84,Pass
4,1005,BBA,Female,72.0,4.0,58.0,6.0,64,Fail
5,1006,CSE,Male,95.0,9.0,88.0,10.0,94,Pass
6,1007,IT,Female,67.0,3.5,52.0,5.0,59,Fail
7,1008,ECE,Male,84.0,6.5,70.0,8.0,77,Pass
8,1009,AI&DS,Female,79.0,6.0,66.0,8.0,73,Pass
9,1010,CSE,Female,93.0,8.5,82.0,10.0,90,Pass
10,1011,BBA,Male,69.0,4.5,55.0,6.0,62,Fail
11,1012,IT,Male,87.0,7.8,76.0,9.0,83,Pass
12,1013,ECE,Female,74.0,5.0,63.0,7.0,69,Fail
13,1014,AI&DS,Male,90.0,8.0,85.0,9.0,88,Pass
14,1015,CSE,Female,81.0,NaN,72.0,8.0,79,Pass
15,1016,IT,Male,78.0,5.8,NaN,7.0,72,Fail
16,1017,ECE,Female,NaN,6.2,67.0,8.0,75,Pass
17,1018,AI&DS,Male,86.0,7.2,73.0,NaN,82,Pass
18,1019,BBA,Female,65.0,3.0,49.0,5.0,55,Fail
19,1020,CSE,Male,89.0,7.5,81.0,9.0,86,Pass
20,1021,IT,Female,83.0,6.8,71.0,8.0,80,Pass
21,1022,ECE,Male,71.0,4.8,59.0,6.0,66,Fail
22,1023,AI&DS,Female,94.0,9.2,89.0,10.0,96,Pass
23,1024,CSE,Male,77.0,5.2,64.0,7.0,71,Pass
24,1025,BBA,Female,73.0,4.2,57.0,6.0,63,Fail
25,1006,CSE,Male,95.0,9.0,88.0,10.0,94,Pass
26,1012,IT,Male,87.0,7.8,76.0,9.0,83,Pass
27,1020,CSE,Male,89.0,7.5,81.0,9.0,86,Pass

In [22]:
# Use the data frame that still contains the rows
dup_count = df.duplicated().sum()
print("Duplicate rows:", dup_count)

Duplicate rows: 3

In [25]:
df_data=df.drop_duplicates()
df_data

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score,pass_fail
0,1001,CSE,Male,82.0,7.5,68.0,9.0,78,Pass
1,1002,IT,Female,91.0,8.2,74.0,10.0,86,Pass
2,1003,ECE,Male,76.0,5.5,61.0,7.0,70,Pass
3,1004,AI&DS,Female,88.0,7.0,79.0,9.0,84,Pass
4,1005,BBA,Female,72.0,4.0,58.0,6.0,64,Fail
5,1006,CSE,Male,95.0,9.0,88.0,10.0,94,Pass
6,1007,IT,Female,67.0,3.5,52.0,5.0,59,Fail
7,1008,ECE,Male,84.0,6.5,70.0,8.0,77,Pass
8,1009,AI&DS,Female,79.0,6.0,66.0,8.0,73,Pass
9,1010,CSE,Female,93.0,8.5,82.0,10.0,90,Pass
10,1011,BBA,Male,69.0,4.5,55.0,6.0,62,Fail
11,1012,IT,Male,87.0,7.8,76.0,9.0,83,Pass
12,1013,ECE,Female,74.0,5.0,63.0,7.0,69,Fail
13,1014,AI&DS,Male,90.0,8.0,85.0,9.0,88,Pass
14,1015,CSE,Female,81.0,NaN,72.0,8.0,79,Pass
15,1016,IT,Male,78.0,5.8,NaN,7.0,72,Fail
16,1017,ECE,Female,NaN,6.2,67.0,8.0,75,Pass
17,1018,AI&DS,Male,86.0,7.2,73.0,NaN,82,Pass
18,1019,BBA,Female,65.0,3.0,49.0,5.0,55,Fail
19,1020,CSE,Male,89.0,7.5,81.0,9.0,86,Pass
20,1021,IT,Female,83.0,6.8,71.0,8.0,80,Pass
21,1022,ECE,Male,71.0,4.8,59.0,6.0,66,Fail
22,1023,AI&DS,Female,94.0,9.2,89.0,10.0,96,Pass
23,1024,CSE,Male,77.0,5.2,64.0,7.0,71,Pass
24,1025,BBA,Female,73.0,4.2,57.0,6.0,63,Fail

In [28]:
df.isnull()

Student_ID               False
Department               False
Gender                   False
Attendance_Pct           False
Study_Hours_Per_Day      False
Internal_Marks           False
Assignments_Completed    False
Final_Score              False
pass_fail                False
dtype: bool

In [27]:
df.isnull().sum()

np.int64(0)

In [75]:
X=df_data.drop("pass_fail",axis=1)
X

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score
0,1001,CSE,Male,82.0,7.5,68.0,9.0,78
1,1002,IT,Female,91.0,8.2,74.0,10.0,86
2,1003,ECE,Male,76.0,5.5,61.0,7.0,70
3,1004,AI&DS,Female,88.0,7.0,79.0,9.0,84
4,1005,BBA,Female,72.0,4.0,58.0,6.0,64
5,1006,CSE,Male,95.0,9.0,88.0,10.0,94
6,1007,IT,Female,67.0,3.5,52.0,5.0,59
7,1008,ECE,Male,84.0,6.5,70.0,8.0,77
8,1009,AI&DS,Female,79.0,6.0,66.0,8.0,73
9,1010,CSE,Female,93.0,8.5,82.0,10.0,90
10,1011,BBA,Male,69.0,4.5,55.0,6.0,62
11,1012,IT,Male,87.0,7.8,76.0,9.0,83
12,1013,ECE,Female,74.0,5.0,63.0,7.0,69
13,1014,AI&DS,Male,90.0,8.0,85.0,9.0,88
14,1015,CSE,Female,81.0,NaN,72.0,8.0,79
15,1016,IT,Male,78.0,5.8,NaN,7.0,72
16,1017,ECE,Female,NaN,6.2,67.0,8.0,75
17,1018,AI&DS,Male,86.0,7.2,73.0,NaN,82
18,1019,BBA,Female,65.0,3.0,49.0,5.0,55
19,1020,CSE,Male,89.0,7.5,81.0,9.0,86
20,1021,IT,Female,83.0,6.8,71.0,8.0,80
21,1022,ECE,Male,71.0,4.8,59.0,6.0,66
22,1023,AI&DS,Female,94.0,9.2,89.0,10.0,96
23,1024,CSE,Male,77.0,5.2,64.0,7.0,71
24,1025,BBA,Female,73.0,4.2,57.0,6.0,63

In [76]:

Y=df["pass_fail"]

In [77]:
X=df_data[[ "Attendance_Pct", "Study_Hours_Per_Day", "Internal_Marks", "Assignments_Completed" ]]

In [78]:
Y=df_data["pass_fail"]

In [80]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
df=pd.read_excel(r"C:\Users\ELCOT\Desktop\Sowmiga\Python Workspace\ML\Practice_data_with_pass_fail.xlsx")
X=df[["Attendance_Pct", "Study_Hours_Per_Day", "Internal_Marks", "Assignments_Completed"]]
y = df["pass_fail"].map({
    "Pass": 1,
    "Fail": 0
})
X_test,Y_test,X_train,Y_train=train_test_split(X,Y,test_size=0.3,random_state=42)
models={ "logistic regression": LogisticRegression(max_iter=1000),
        "Decision tree": DecisionTreeClassifier(max_depth=5,random_state=42),
        "random forest": RandomForestClassifier(n_estimators=100, random_state=42)}
for name,model in models.items():
    model.fit (X_train,Y_train)
    y_pred=model.predict(X_test)
    print(f"\n{name}")
    print(classification_report(Y_test,y_pred,zero_division=0))

ValueError: could not convert string to float: 'Pass'